config/routes.rb
Rails.application.routes.draw do
    
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  resources :users, excpet: [:show]
  get "users/cancel/:id", to: "users#cancel", as: "users_cancel"
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  root "fdn/foundations#index"

  scope module: 'fdn' do
    # charts
    get "foundation/:foundation_id/charts/top-donors", to: "charts#top_donors", as: "charts_top_donors"
    get "foundation/:foundation_id/charts/contribution-time-line", to: "charts#contribution_time_line", as: "charts_contribution_time_line"
    
    get "foundation/cancel", to: "foundations#cancel"
    resources :foundations, except: [:show] do
      get "dashboard", on: :member
      get "settings", on: :member
      delete "remove-image-logo", to: "foundations#remove_image_logo", as: "remove_image_logo"
      delete "remove-image-header", to: "foundations#remove_image_header", as: "remove_image_header"
      namespace "reporting" do
        get "dashboard", to: "reports#dashboard"
        get "organization_list", to: "reports#organization_list"
        get "commitment", to: "reports#get_commitment"
        get "contribution", to: "reports#get_contribution"
        post "commitment_report", to: "reports#show_commitment"
        post "contribution_report", to: "reports#show_contribution"
      end
      get "organizations/sort", to: "organizations#sort"
      resources :organizations do
        get "cancel", on: :member
        get "contributions", on: :member
        get "commitments", on: :member
      end
      scope module: 'accounting' do
        resources :bank_accounts do 
          get "cancel", on: :member
          resources :checks, shallow: true, except: [:show]
          get "reconciliations/cancel", to: "reconciliations#cancel"
          post "reconciliations/new_next", to: "reconciliations#new_next"
          resources :reconciliations, shallow: true, except: [:edit, :update]
        end
      end
      scope module: 'donations' do
        get "contributions/new_next", to: "contributions#new_next"
        get "commitments/new_next", to: "commitments#new_next"
        get "contributions/sort", to: "contributions#sort"
        get "commitments/sort", to: "commitments#sort"
        resources :contributions do
          get "cancel", on: :member
        end
        resources :commitments do
          get "cancel", on: :member
          get "contribution/new", to: "commitments#new_contribution"
          post "contributions", to: "commitments#create_contribution"
          get "contribution/:id", to: "commitments#edit_contribution", as: "contribution"
          patch "contribution/:id", to: "commitments#update_contribution"
          delete "contribution/:id", to: "commitments#destroy_contribution"
        end
      end
      namespace :settings do
        resources :donors, except: [:show]
        resources :funding_sources, except: [:show]
        resources :organization_types, except: [:show]
      end
    end
  end

end

app/models/reconciliation.rb
class Reconciliation < ApplicationRecord
  belongs_to :bank_account
  has_many :reconciliation_items, dependent: :destroy
  has_many :checks, through: :reconciliation_items

  monetize :starting_balance_cents, numericality: true
  monetize :ending_balance_cents, numericality: true
  
  validates :started_at, :ended_at, presence: true
  validates :started_at, comparison: { less_than: :ended_at }
  validate :validate_date_range_uniqueness

  after_initialize :set_starting_values
  after_create :set_checks_cleared

  scope :bank_reconciliations, -> (bank_account_id) { where(bank_account_id: bank_account_id).order(started_at: :desc) }


  private

    def set_checks_cleared
      checks.update_all(cleared: true)
    end

    def set_starting_values
      if new_record? && bank_account_id.present?
        last_reconciliation =  Reconciliation.bank_reconciliations(bank_account_id).first
        if last_reconciliation.present?
          self.started_at = last_reconciliation.ended_at + 1.day
          self.starting_balance = last_reconciliation.ending_balance
        else
          bank_account = BankAccount.find(bank_account_id).checks.where(transaction_type: :credit).order(transaction_at: :asc).first
          if bank_account.present?
            self.started_at = bank_account.transaction_at
            self.starting_balance = 0
          end
        end
      end
    end

    def validate_date_range_uniqueness
      return unless started_at && ended_at  
      if Reconciliation.exists?(['(bank_account_id = ?) AND ((started_at <= ? AND ended_at >= ?) OR (started_at <= ? AND ended_at >= ?))',
              bank_account_id, started_at, started_at, ended_at, ended_at])
        errors.add(:base, 'Date range is already in use.')
      end
    end    
end

app/controllers/fdn/accounting/bank_accounts_controller.rb
class Fdn::Accounting::BankAccountsController < Fdn::BaseController
  before_action :set_bank_account, only: %i[ show edit update destroy ]

  def index
    @bank_accounts = @foundation.bank_accounts
    @primary_account = @bank_accounts.where(primary: true).take
    render turbo_stream: [
      turbo_stream.replace("main_content", partial: "index")
    ]  
  end

  def show
    render turbo_stream: [
      turbo_stream.replace("bank_account_main", partial: "main", locals: { bank_account: @bank_account })
    ]
  end

  def new
    @bank_account = BankAccount.new
  end

  def cancel
    if params[:id].to_i != -1
      set_bank_account
      render turbo_stream: [
        turbo_stream.replace(@bank_account, partial: "bank_account", locals: {bank_account: @bank_account})
      ]
    else
      render turbo_stream: [
        turbo_stream.replace(BankAccount.new, partial: "new_button", locals: {bank_accounts: @foundation.bank_accounts})
      ]
    end
  end

  def edit
  end

  def create
    @bank_account = @foundation.bank_accounts.new(bank_account_params)
    if @bank_account.save
      flash.now[:notice] = "Bank account was successfully created."
      render turbo_stream: [ 
        turbo_stream.replace(BankAccount.new, partial: "new_button", locals: {bank_accounts: @foundation.bank_accounts} ),
        turbo_stream.replace("messages", partial: "layouts/messages")
      ]
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @bank_account.update(bank_account_params)
      flash.now[:notice] = "Bank account was successfully updated."
      render turbo_stream: [
        turbo_stream.replace(BankAccount.new, partial: "new_button", locals: {bank_accounts: @foundation.bank_accounts} ),
        turbo_stream.replace("bank_account_main", partial: "main", locals: {bank_account: @bank_account, checks: @bank_account.checks}),
        turbo_stream.replace("messages", partial: "layouts/messages")
      ]   
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @bank_account.destroy
      flash.now[:notice] = "Bank account was successfully deleted."
      render turbo_stream: [
        turbo_stream.replace(BankAccount.new, partial: "new_button", locals: {bank_accounts: @foundation.bank_accounts} ),
        turbo_stream.replace("bank_account_main", partial: "main_empty"),
        turbo_stream.replace("messages", partial: "layouts/messages")
      ]
    else
      flash.now[:notice] = "Bank account cannot be deleted. Because it has transactions"
      render turbo_stream: [
        turbo_stream.replace("messages", partial: "layouts/messages")
      ]
    end
  end

  private

    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    def bank_account_params
      params.require(:bank_account).permit(:full_name, :primary, :starting_balance)
    end
end

app/controllers/fdn/accounting/checks_controller.rb
class Fdn::Accounting::ChecksController < Fdn::BaseController
  before_action :set_bank_account, only: %i[ new index ]
  before_action :set_check, only: %i[ edit update destroy ]

  def index
    @checks = @bank_account.checks.open_deposits
  end

  def new
   @check = Check.new
  end

  def create
    @check = Check.new(check_params)
    @check.transaction_type = :credit
    if @check.save
      set_bank_account
      flash.now[:notice] = "Deposit was added."
      render turbo_stream: [ 
        turbo_stream.replace(@bank_account, partial: "fdn/accounting/bank_accounts/bank_account", locals: { bank_account: @bank_account }),
        turbo_stream.replace("bank-deposits", partial: "checks_list", locals: { checks: @bank_account.checks.open_deposits }),
        turbo_stream.replace("messages", partial: "layouts/messages")
      ]
    else
      set_bank_account
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @check.update(check_params)
      flash.now[:notice] = "Deposit was successfully updated."
      render turbo_stream: [
        turbo_stream.replace(@bank_account, partial: "fdn/accounting/bank_accounts/bank_account", locals: { bank_account: @bank_account }),
        turbo_stream.replace("bank-deposits", partial: "checks_list", locals: { checks: @bank_account.checks.open_deposits }),
        turbo_stream.replace("messages", partial: "layouts/messages")
      ]   
    else
      render :edit, status: :unprocessable_entity
    end  
  end

  def destroy
    if !@check.cleared
      @check.destroy
      flash.now[:notice] = "Deposit was successfully removed."
      render turbo_stream: [
        turbo_stream.replace(@bank_account, partial: "fdn/accounting/bank_accounts/bank_account", locals: { bank_account: @bank_account }),
        turbo_stream.replace("bank-deposits", partial: "checks_list", locals: { checks: @bank_account.checks.open_deposits }),
        turbo_stream.replace("messages", partial: "layouts/messages")
      ]
    else
      flash.now[:notice] = "Deposit has already been cleared. Cannot remove."
      render turbo_stream: [
        turbo_stream.replace("messages", partial: "layouts/messages")
      ]
    end
  end

  private

  def set_check
    @check = Check.find(params[:id])
    @bank_account = @check.bank_account
    @foundation = @bank_account.foundation
  end

  def set_bank_account
    @bank_account = BankAccount.find(params[:bank_account_id])
  end

  def check_params
    params.require(:check).permit(:transaction_at, :description, :amount, :bank_account_id)
  end

end

app/controllers/fdn/accounting/reconciliations_controller.rb
class Fdn::Accounting::ReconciliationsController < Fdn::BaseController
  before_action :set_bank_account, only: %i[ index new cancel new_next create ]
  before_action :set_reconciliation, only: %i[ show destroy ]

  def show
    
  end 

  def index
    @reconciliations = @bank_account.reconciliations
  end

  def new
    @reconciliation = @bank_account.reconciliations.new
  end

  def cancel
    @reconciliations = @bank_account.reconciliations
    render turbo_stream: [
      turbo_stream.replace("reconciliation-main", partial: "reconciliations_list")
    ]
  end

  def new_next
    @reconciliation = @bank_account.reconciliations.new(reconciliation_params)
    if @reconciliation.valid?
      @checks = @bank_account.checks.open_transactions
    else
      render :new, status: :unprocessable_entity
    end
  end

  def create
    @reconciliation = @bank_account.reconciliations.new(reconciliation_params)
    if @reconciliation.save
      @reconciliations = @bank_account.reconciliations
      flash.now[:notice] = "Successfully reconciled statement."
        render turbo_stream: [
          turbo_stream.replace("messages", partial: "layouts/messages"),
          turbo_stream.replace("reconciliation-main", partial: "reconciliations_list")
        ]
    else
      render :new_next, status: :unprocessable_entity
    end
  end

  def destroy
    @reconciliation.destroy
    @reconciliations = @bank_account.reconciliations
    flash.now[:notice] = "Reconciliation was successfully removed."
    render turbo_stream: [
          turbo_stream.replace("messages", partial: "layouts/messages"),
          turbo_stream.replace("reconciliation-main", partial: "reconciliations_list")
        ]
  end

  private

  def set_reconciliation
    @reconciliation = Reconciliation.find(params[:id])
    @bank_account = @reconciliation.bank_account
    @foundation = @bank_account.foundation
  end

  def set_bank_account
    @bank_account = BankAccount.find(params[:bank_account_id])
  end

  def reconciliation_params
    params.require(:reconciliation).permit( :bank_account_id, :started_at, :ended_at, 
      :starting_balance, :ending_balance, :check_ids => [] )
  end

end

app/views/fdn/accounting/reconciliations/_form.html.erb
<%= form_with model: reconciliation, url: form_url, id: dom_id(reconciliation, "form"), class: "pb-1 ps-1" do |f| %>

 <%= f.hidden_field :bank_account_id, value: @bank_account.id %>

  <div class="container pt-2">
    <div class="row justify-content-center">
      <div class="col-md-9">
        <%= render 'shared/error_messages', resource: reconciliation %>
      </div>
    </div>
  </div>

  <div class="row pb-1">
    <div class="col-sm-3">
      <%= f.label :started_at, "Start" %>
    </div>
    <div class="col-sm-3">
      <%= f.date_field :started_at, class: "form-control form-control-sm" %>  
    </div>
    <div class="col-sm-3">
      <%= f.label :ended_at, "End" %>
    </div>
    <div class="col-sm-3">
      <%= f.date_field :ended_at, class: "form-control form-control-sm" %>  
    </div>
  </div>
  
  <div class="row pt-1 pb-2">
    <div class="col-sm-3">
      <%= f.label :starting_balance %>
    </div>
    <div class="col-sm-3">
      <%= f.text_field :starting_balance, class: "form-control form-control-sm text-end" %>  
    </div>
    <div class="col-sm-3">
      <%= f.label :ending_balance %>
    </div>
    <div class="col-sm-3">
      <%= f.text_field :ending_balance, class: "form-control form-control-sm text-end" %>
    </div>
  </div>

  <div class="row border-top border-info mx-0 py-1">
    <div class="col-4 text-start">
      <%= link_to foundation_bank_account_reconciliations_cancel_path(@foundation, @bank_account), class: "btn btn-outline-info btn-sm" do %>
        <i class="bi calendar2-plus pe-1"></i>Cancel
      <% end %> 
    </div>
    <div class="col-5 offset-3 text-end">
      <%= f.button class: "btn btn-sm btn-outline-info text-start" do %>
          <i class="bi bi-plus-circle pe-1"></i>Next
      <% end %>
    </div>
  </div>
<% end %>

app/views/fdn/accounting/reconciliations/_reconciliation.html.erb
<%#= turbo_frame_tag reconciliation do %>
  <div class="row my-table-row mx-0">
    <div class="col-4 col-sm-2 px-1 pt-1 my-0 border border-secondary-subtle border-end-0 border-start-0">
      <%= reconciliation.started_at.strftime("%m/%d/%Y") %>
    </div>
    <div class="d-none d-sm-block col-sm-4 ps-1 pe-3 pt-1 my-0 border border-secondary-subtle border-end-0 border-start-0 text-end">
      <%= reconciliation.starting_balance.format %>
    </div>
    <div class="col-4 ps-1 pe-3 pt-1 my-0 border border-secondary-subtle border-end-0 border-start-0 text-end">
      <%= reconciliation.ending_balance.format %>
    </div>
    <div class="col-2 px-1 my-0 text-center">
      <div class="btn-group">
        <%= link_to reconciliation_path(reconciliation), class: "btn btn-sm btn-outline-secondary" do %>
          <i class="bi bi-binoculars pe-1"></i>
        <% end %>
        <%= button_to reconciliation_path(reconciliation), method: :delete, class: "btn btn-sm btn-outline-danger", 
              form: {data: {turbo_confirm: 'Are you sure?'}} do %>
          <i class="bi bi-trash pe-1"></i>
        <% end %>         
      </div>
    </div>
  </div>
<%# end %> 

app/views/fdn/accounting/reconciliations/_reconciliations_list.html.erb
<%= turbo_frame_tag "reconciliation-main" do %>
  <div class="row tb-header mx-0 py-1 align-items-center mb-1">
    <div class="col-4 col-sm-2">Date</div>
    <div class="d-none d-sm-block col-sm-4 text-center">Opening Balance</div>
    <div class="col-4 text-center">Ending Balance</div>
    <div class="col-2">
      <%# , data: { turbo_frame: "new_reconciliation" } %>
      <%= link_to new_foundation_bank_account_reconciliation_path(@foundation, @bank_account), class: "btn btn-outline-success btn-sm py-0" do %>
        <i class="bi calendar2-plus pe-1"></i>Reconcile
      <% end %>          
    </div>
  </div>

  <%= render @reconciliations %>  
<% end %>

app/views/fdn/accounting/reconciliations/index.html.erb
<%= turbo_frame_tag "bank-account-sub" do %>
  <%= render "fdn/accounting/nav" %>

  <div class="border border-top-0">
    <div class="container-fluid px-0 pt-4 pb-2">
      <%= render "reconciliations_list" %>
    </div>
  </div>
<% end %>

app/views/fdn/accounting/reconciliations/new.html.erb
<%= turbo_frame_tag "reconciliation-main" do %>
  <div class="card bg-info bg-opacity-10 border-info px-2 mx-1">
      <%= render "form", reconciliation: @reconciliation, form_url: foundation_bank_account_reconciliations_new_next_path(@foundation, @bank_account) %>
  </div>
<% end %>

app/views/fdn/accounting/reconciliations/new_next.html.erb
<%= turbo_frame_tag "reconciliation-main" do %>
  <div class="card bg-info bg-opacity-10 border-info p-2" data-controller="reconciliation" 
              data-reconciliation-reconciliationbalance-value="<%= @reconciliation.ending_balance_cents - @reconciliation.starting_balance_cents  %>" >
    <div class="row align-items-center">
      <div class="col-auto">
        <span class="badge rounded-pill bg-info">Statement Date : </span>
      </div>
      <div class="col">
        <%= "#{@reconciliation.started_at.strftime("%m/%d/%Y")} - #{@reconciliation.ended_at.strftime("%m/%d/%Y")}" %>
      </div>
    </div>
    <div class="row align-items-center pb-2">
      <div class="col-md-2">
        <span class="badge rounded-pill bg-info">Starting Balance : </span>
      </div>
      <div class="col-md-2 text-center">
        <%= @reconciliation.starting_balance.format %>
      </div>
      <div class="col-md-2">
        <span class="badge rounded-pill bg-info">Ending Balance : </span>
      </div>
      <div class="col-md-2 text-center">
        <%= @reconciliation.ending_balance.format %>
      </div>
      <div class="col-md-2">
        <span class="badge rounded-pill bg-info">Balance : </span>
      </div>
      <div class="col-md-2 text-center">
        <span data-reconciliation-target="balance"></span>
      </div>
    </div>
    <%= form_with model: @reconciliation, url: foundation_bank_account_reconciliations_path(@foundation, @bank_account), 
          id: dom_id(@reconciliation, "form"), class: "pb-1 ps-1" do |f| %>
      <%= f.hidden_field :bank_account_id, value: @reconciliation.bank_account_id %>
      <%= f.hidden_field :started_at, value: @reconciliation.started_at %>
      <%= f.hidden_field :ended_at, value: @reconciliation.ended_at %>
      <%= f.hidden_field :starting_balance, value: @reconciliation.starting_balance %>
      <%= f.hidden_field :ending_balance, value: @reconciliation.ending_balance %>
      <%= f.hidden_field :journal_entry, value: "", data: { :"reconciliation-target" => "journal" } %>

      <div class="row gx-5 pb-2">
        <div class="col-auto">
          <div class="card bg-info bg-opacity-10 border-info h-100">
            <div class="card-header py-0 text-center">Deposits</div>
            <div class="card-body p-2">           
              <% @checks.each do |check| %>
                <% if check.credit? %>
                  <div class="form-check px-1">
                    <%= f.check_box :check_ids, { multiple: true, data: { value: "#{check.amount_cents}", action: "click->reconciliation#update_balance" } }, 
                    check.id, nil %>
                    <label for="reconciliation_check_ids<%= "_#{check.id}" %>">
                      <%= "#{check.transaction_at.strftime("%m/%d/%Y")} #{check.amount.format}" %>
                    </label>
                    
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card bg-info bg-opacity-10 border-info h-100">
            <div class="card-header py-0 text-center">Contributions</div>
            <div class="card-body p-2">
              <% @checks.each do |check| %>
                <% if check.debit? %>
                  <div class="form-check px-1">
                    <%= f.check_box :check_ids, { multiple: true, data: { value: "-#{check.amount_cents}", action: "click->reconciliation#update_balance" } }, check.id, nil %>
                    <label for="reconciliation_check_ids<%= "_#{check.id}" %>">
                      <%= "#{check.transaction_at.strftime("%m/%d/%Y")} #{check.check_number} #{check.amount.format}" %>
                    </label>
                    
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="row border-top border-info mx-0 py-1">
        <div class="col-sm-4 text-start">
          <%= link_to foundation_bank_account_reconciliations_cancel_path(@foundation, @bank_account), class: "btn btn-outline-info btn-sm" do %>
            <i class="bi calendar2-plus pe-1"></i>Cancel
          <% end %> 
        </div>
        <div class="col-sm-4 offset-4 text-end">
          <%= f.button class: "btn btn-sm btn-outline-info text-start", data: { action: "reconciliation#reconcile" } do %>
              <i class="bi bi-plus-circle pe-1"></i>Reconcile
          <% end %>
        </div>
      </div>
    <% end %>

  </div>
<% end %>

app/views/fdn/accounting/reconciliations/show.html.erb
<%= turbo_frame_tag "reconciliation-main" do %>
  <div class="card bg-info bg-opacity-10 border-info mx-1">
    <div class="card-header bg-info bg-opacity-25 px-1">
      <div class="row align-items-center mx-0">
        <div class="col-auto px-1">
          <span class="badge rounded-pill bg-info">Statement : </span>
        </div>
        <div class="col px-1">
          <%= "#{@reconciliation.started_at.strftime("%m/%d/%Y")} - #{@reconciliation.ended_at.strftime("%m/%d/%Y")}" %>
        </div>
      </div>
    </div>
    <div class="card-body px-1">

      <div class="row align-items-center pb-2 mx-0">
        <div class="col-5 col-md-2">
          <span class="badge rounded-pill bg-info">Starting Balance : </span>
        </div>
        <div class="col-6 col-md-4 text-center">
          <%= @reconciliation.starting_balance.format %>
        </div>
        <div class="col-5 col-md-2">
          <span class="badge rounded-pill bg-info">Ending Balance : </span>
        </div>
        <div class="col-6 col-md-4 text-center">
          <%= @reconciliation.ending_balance.format %>
        </div>
      </div>

      <div class="card bg-info bg-opacity-10 border-info">
        <div class="card-header py-0 text-center">Transactions</div>
        <div class="card-body px-0 py-2">           
          <% @reconciliation.checks.each do |check| %>

            <div class="row mx-0 <%=  "bg-success bg-opacity-10" if check.credit? %>">
              <div class="col-4 col-md-2 px-1">
                <%= check.transaction_at.strftime("%m/%d/%Y") %>
              </div>
              <div class="d-none d-md-block col-md-1 px-1">
                <%= check.debit? ? check.check_number : "DEP" %>
              </div>
              <div class="d-none d-md-block col-md-5 px-1">
                <%= check.debit? ? check.contribution.organization.name : check.description %>
              </div>
              <div class="col-6 col-md-4 px-2 text-end">
                <%= "#{check.debit? ? "-" : "+"} #{check.amount.format}" %>
              </div>
            </div>
            
          <% end %>
        </div>
      </div>

    </div>
  </div>
<% end %>