config/routes.rb
Rails.application.routes.draw do
    
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  resources :users, excpet: [:show]
  get "users/cancel/:id", to: "users#cancel", as: "users_cancel"
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  root "fdn/foundations#index"

  scope module: 'fdn' do
    # charts
    get "foundation/:foundation_id/charts/top-donors", to: "charts#top_donors", as: "charts_top_donors"
    get "foundation/:foundation_id/charts/contribution-time-line", to: "charts#contribution_time_line", as: "charts_contribution_time_line"
    
    get "foundation/cancel", to: "foundations#cancel"
    resources :foundations, except: [:show] do
      get "dashboard", on: :member
      get "settings", on: :member
      delete "remove-image-logo", to: "foundations#remove_image_logo", as: "remove_image_logo"
      delete "remove-image-header", to: "foundations#remove_image_header", as: "remove_image_header"
      namespace "reporting" do
        get "dashboard", to: "reports#dashboard"
        get "organization_list", to: "reports#organization_list"
        get "commitment", to: "reports#get_commitment"
        get "contribution", to: "reports#get_contribution"
        post "commitment_report", to: "reports#show_commitment"
        post "contribution_report", to: "reports#show_contribution"
      end
      get "organizations/sort", to: "organizations#sort"
      resources :organizations do
        get "cancel", on: :member
        get "contributions", on: :member
        get "commitments", on: :member
      end
      scope module: 'accounting' do
        resources :bank_accounts do 
          get "cancel", on: :member
          resources :checks, shallow: true, except: [:show]
          get "reconciliations/cancel", to: "reconciliations#cancel"
          post "reconciliations/new_next", to: "reconciliations#new_next"
          resources :reconciliations, shallow: true, except: [:edit, :update]
        end
      end
      scope module: 'donations' do
        get "contributions/new_next", to: "contributions#new_next"
        get "commitments/new_next", to: "commitments#new_next"
        get "contributions/sort", to: "contributions#sort"
        get "commitments/sort", to: "commitments#sort"
        resources :contributions do
          get "cancel", on: :member
        end
        resources :commitments do
          get "cancel", on: :member
          get "contribution/new", to: "commitments#new_contribution"
          post "contributions", to: "commitments#create_contribution"
          get "contribution/:id", to: "commitments#edit_contribution", as: "contribution"
          patch "contribution/:id", to: "commitments#update_contribution"
          delete "contribution/:id", to: "commitments#destroy_contribution"
        end
      end
      namespace :settings do
        resources :donors, except: [:show]
        resources :funding_sources, except: [:show]
        resources :organization_types, except: [:show]
      end
    end
  end

end

app/controllers/fdn/reporting/reports_controller.rb
class Fdn::Reporting::ReportsController < Fdn::BaseController

  def dashboard
    render turbo_stream: [
      turbo_stream.replace("main_content", partial: "dashboard")
    ]    
  end

  def organization_list
    set_organization_filter_params
    @organizations = OrganizationsFilter.new.process_request(@foundation.organizations, @query, @by, (@dir == 1 ? @dir = 2 : @dir = 1))
    pdf = generate_pdf("Organization List", nil, "Portrait", "fdn/reporting/organizations/list")
    send_data(pdf, filename: "organization_list", type: "application/pdf", disposition: :inline)  
  end

  def get_commitment
  end

  def get_contribution
  end

  def show_contribution
    contribution_report_form = ContributionReportForm.new(contribution_params)
    @start_at = Date.parse(contribution_report_form.starting_date)
    @end_at = Date.parse(contribution_report_form.ending_date)
    if contribution_report_form.types.include?("0")
      org_ids = @foundation.organization_ids
    else
      org_ids = @foundation.organizations.types(contribution_report_form.types)
    end
    @contributions = Contribution.organization_contributions(org_ids).transactions_during(@start_at, @end_at)
    if !contribution_report_form.funds.include?("0")
      @contributions = @contributions.funds(contribution_report_form.funds)
    end
    if !contribution_report_form.donors.include?("0")
      @contributions = @contributions.donors(contribution_report_form.donors)
    end
    @contributions = @contributions.sort_date_up
    pdf = generate_pdf("Contributions", "fdn/reporting/contributions/header", "Portrait", "fdn/reporting/contributions/summary")
    send_data(pdf, filename: "contribution_report", type: "application/pdf", disposition: :inline)
  end

  def show_commitment
    commitment_report_form = CommitmentReportForm.new(commitment_params)
    if commitment_report_form.state == "open" && commitment_report_form.sort == "alpha"
      @commitments = Commitment.organization_commitments(@foundation.organization_ids).not_completed.sort_organization_up
    elsif commitment_report_form.state == "open" && commitment_report_form.sort == "date"
      @commitments = Commitment.organization_commitments(@foundation.organization_ids).not_completed.sort_start_date_up
    elsif commitment_report_form.state == "closed" && commitment_report_form.sort == "date"
      @commitments = Commitment.organization_commitments(@foundation.organization_ids).completed.sort_start_date_up
    else
      @commitments = Commitment.organization_commitments(@foundation.organization_ids).completed.sort_organization_up
    end
    if commitment_report_form.format == "detailed"
      additional_header = nil
      template = "fdn/reporting/commitments/detailed"
      orientation = "Portrait"
    else
      additional_header = "fdn/reporting/commitments/summary_header"
      template = "fdn/reporting/commitments/summary"
      orientation = "Landscape"
    end
    pdf = generate_pdf("Commitments", additional_header, orientation, template)
    send_data(pdf, filename: "commitment_report", type: "application/pdf", disposition: :inline)  
  end

  private

  def commitment_params
    params.require(:commitment_report_form).permit(:format, :state, :sort)
  end

  def contribution_params
    params.require(:contribution_report_form).permit(:starting_date, :ending_date, funds:[], donors:[], types:[])
  end

  def generate_pdf(title, additional_header, orientation, template)
    WickedPdf.new.pdf_from_string(
      render_to_string(template: template, formats: [:html], layout: "pdf" ),
      # margin: { top: 10, bottom: 10, left: 10, right: 10 }, 
      header: { content: render_to_string(template: "shared/pdf/header", 
                  formats: [:html], 
                  layout: "pdf_section", 
                  locals: { title: title, additional_header: additional_header })
              },
      footer: { content: render_to_string(template: "shared/pdf/footer", 
                  formats: [:html], 
                  layout: "pdf_section") 
                  # right: "[page] of [topage]" 
              },
              orientation: orientation
    )  
  end
  
end

app/views/fdn/reporting/reports/_commitment_summary_header.html.erb
<div class="table">
  <div class="row header ps-1 pt-1">
    <div class="col w-15">Organization</div>
    <div class="col w-11">Commitment Code</div>
    <div class="col w-5">Start</div>
    <div class="col w-5">End</div>
    <div class="col w-5">
      <div class="table">
        <div class="row">
          <div class="col">Payments</div>          
        </div>
        <div class="row">
          <div class="col w-2">#</div>
          <div class="col w-2">Made</div>
        </div>
      </div>
    </div>
    <div class="col w-5">Last</div>
    <div class="col w-7 text-end pe-1">Total</div>
    <div class="col w-7 text-end pe-1">Paid</div>
    <div class="col w-7 text-end pe-1">Due</div>
  </div>
</div>

app/views/fdn/reporting/reports/_dashboard.html.erb
<div id="main_content" data-controller="pages" 
      data-pages-sbnum-value="4"
      data-pages-sidebar-outlet="#sidebar-controller">

  <div class="card">
    <div class="card-header text-center my-header">
      <div class="row">
        <div class="col-auto"><%= image_tag(@foundation.resize_image_logo(25,25)) if @foundation.image_logo.attached? %></div>
        <div class="col text-center"><h5 class="mb-0">Reports</h5></div>
      </div>
    </div>

    <div class="container py-2" data-controller="reports">
      <div class="row">
        <div class="col-auto">
          <div class="btn-group-vertical">
            <%= link_to foundation_reporting_commitment_path(@foundation), class: "btn btn-sm btn-outline-secondary",  
                  data: { turbo_frame: 'report_form' },
                  "data-action": "click->reports#toggle",
                  "data-reports-target": "btn" do %>
              <i class="bi bi-file-earmark-pdf me-2"></i>
              Commitments
            <% end %>

            <%= link_to foundation_reporting_contribution_path(@foundation), class: "btn btn-sm btn-outline-secondary",  
                  data: { turbo_frame: 'report_form' },
                  "data-action": "click->reports#toggle",
                  "data-reports-target": "btn" do %>
              <i class="bi bi-file-earmark-pdf me-2"></i>
              Contributions
            <% end %>
          </div>
        </div>
        <div class="col">
          <div class="card small py-1 mb-1">
            <%= render "fdn/reporting/commitments/form" %>
          </div>
        </div>
      </div>


    </div>
    
  </div>
</div>

app/views/fdn/reporting/reports/commitment_detailed.html.erb
<% provide(:title, "#{@foundation.short_name} Commitment Report") %>

<% last_index = @commitments.size - 1 %>
<% @commitments.each_with_index do |commitment, index| %>
  <div class="table">
    <div class="row">
      <div class="col w-30 text-top me-3 h-100">
        <div class="row">
          <div class="col text-bold text-italic">Organization :</div>
        </div>
        <div class="row">
          <div class="col ps-2 text-300 text-italic"><%= commitment.organization.contact %></div>
        </div>
        <div class="row">
          <div class="col text-500 ps-2"><%= commitment.organization.name.upcase %></div>
        </div>
        <div class="row">
          <div class="col ps-2"><%= commitment.organization.address_1 %></div>
        </div>
        <% if commitment.organization.address_2.present? %>
          <div class="row">
            <div class="col ps-2"><%= commitment.organization.address_2 %></div>
          </div>
        <% end %>
        <div class="row">
          <div class="col ps-2">
            <%= "#{commitment.organization.city}, #{commitment.organization.state} #{commitment.organization.zip}" %>
          </div>
        </div>
        <% if commitment.organization.country.present? %>
          <div class="row">
            <div class="col ps-4"><%= commitment.organization.country %></div>
          </div>
        <% end %>        
      </div>
      <div class="col w-22 text-top h-100">
        <div class="row">
          <div class="col text-bold text-italic">Type :</div>
        </div>
        <div class="row">
          <div class="col ps-2">
            <%= commitment.organization.organization_type.code %>
          </div>
        </div>
        <div class="row pt-4">
          <div class="col text-bold text-italic">Commitment Code :</div>
        </div>
        <div class="row">
          <div class="col ps-2">
            <%= commitment.code %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col w-100p"><hr class="black-line pt-0"></div>
    </div>
    <div class="row">
      <div class="col w-11 me-2">
        <%== "<b># of Payments :</b> #{commitment.number_payments}" %>
      </div>
      <div class="col w-20 me-2">
        <%== "<b>Payment Amount : </b>#{commitment.amount.format}" %>
      </div>
      <div class="col w-20">
        <%== "<b>Total Commitment : </b>#{Money.new(commitment.total_commitment).format}" %>
      </div>
    </div>
    <div class="row pt-2">
      <div class="col w-11 me-2">
        <%== "<b>Start Date : </b>#{commitment.start_at.strftime("%m/%d/%Y")}" %>
      </div>
      <div class="col w-11">
        <%== "<b>End Date : </b>#{commitment.end_at.strftime("%m/%d/%Y")}" %>
      </div>
    </div>
    <div class="row">
      <div class="col w-100p"><hr class="black-line pt-0"></div>
    </div>
    <div class="table ms-4 mt-2">
      <div class="row text-bold text-italic">
        <div class="col w-8 text-end me-2">Payment</div>
        <div class="col w-6">Date</div>
        <div class="col w-5">Check #</div>
        <div class="col w-7">Fund</div>
        <div class="col w-24">Description</div>
      </div>
      <% commitment.contributions.each do |contribution| %>
        <div class="row pt-1">
          <div class="col w-8 text-end me-2">
            <%= contribution.check.amount.format %>
          </div>
          <div class="col w-6">
            <%= contribution.check.transaction_at.strftime("%m/%d/%Y") %>
          </div>
          <div class="col w-5">
            <%= contribution.check.check_number %>
          </div>
          <div class="col w-7">
            <%= contribution.funding_source.short_name %>
          </div>
          <div class="col w-24">
            <%= contribution.check.description %>
          </div>
        </div>
      <% end %>
      <div class="row">
        <div class="col w-1"></div>
        <div class="col w-7"><hr class="black-line"></div>
      </div>
      <div class="row">
        <div class="col w-8 text-end pe-2"><%= Money.new(commitment.payments).format %></div>
      </div>
    </div>
  </div>
  <%== "<div class='alwaysbreak'></div>" unless last_index == index %>
<% end %>

app/views/fdn/reporting/reports/commitment_summary.html.erb
<% provide(:title, "#{@foundation.short_name} Commitment Report") %>

<div class="table">
  <% proposed_payments_total = 0 %>
  <% payments_made_total = 0 %>
  <% total_commitment = 0 %>
  <% total_commitment_payed = 0 %>
  <% total_commitment_due = 0 %>

  <% @commitments.each do |commitment| %>

    <% proposed_payments_total += commitment.number_payments %>
    <% payments_made_total += commitment.contributions.size %>
    <% total_commitment += commitment.total_commitment %>
    <% total_commitment_payed += commitment.payments %>
    <% total_commitment_due += commitment.amount_due %>
  
    <div class="row ps-1 pt-1">
      <div class="col w-15"><%= commitment.organization.name %></div>
      <div class="col w-11"><%= commitment.code %></div>
      <div class="col w-5"> <%= commitment.start_at.strftime("%m/%d/%Y") %></div>
      <div class="col w-5"> <%= commitment.end_at.strftime("%m/%d/%Y") %></div>
      <div class="col w-2 text-center"><%= commitment.number_payments %></div>
      <div class="col w-2 text-center"><%= commitment.contributions.size %></div>
      <div class="col w-1"></div>
      <div class="col w-5">
        <%= commitment.contributions.sort_date_down.first.check.transaction_at.strftime("%m/%d/%Y") if commitment.contributions.size > 0 %>
      </div>
      <div class="col w-7 text-end"><%= Money.new(commitment.total_commitment).format %></div>
      <div class="col w-7 text-end"><%= Money.new(commitment.payments).format %></div>
      <div class="col w-7 text-end"><%= Money.new(commitment.amount_due).format %></div>
    </div>
  <% end %>
  <div class="row ps-1 pt-4">
    <div class="col w-26"></div>
    <div class="col">
      <div class="row footer ps-1 pt-1">
        <div class="col w-10"> Report Totals</div>
        <div class="col w-2 text-center"><%= proposed_payments_total %></div>
        <div class="col w-2 text-center"><%= payments_made_total %></div>
        <div class="col w-6"></div>
        <div class="col w-7 text-end"><%= Money.new(total_commitment).format %></div>
        <div class="col w-7 text-end"><%= Money.new(total_commitment_payed).format %></div>
        <div class="col w-7 text-end pe-1"><%= Money.new(total_commitment_due).format %></div>
      </div>
    </div>
  </div>
</div>

app/views/fdn/reporting/reports/get_commitment.html.erb
<%= render "fdn/reporting/commitments/form" %>

app/views/fdn/reporting/reports/get_contribution.html.erb
<%= render "fdn/reporting/contributions/form" %>

app/views/fdn/reporting/reports/old_dashboard.html.erb
<div id="main_content" data-controller="pages" 
      data-pages-sbnum-value="4"
      data-pages-sidebar-outlet="#sidebar-controller">

  <div class="card">
    <div class="card-header text-center my-header">
      <div class="row">
        <div class="col-auto"><%= image_tag(@foundation.resize_image_logo(25,25)) if @foundation.image_logo.attached? %></div>
        <div class="col text-center"><h5 class="mb-0">Reports</h5></div>
      </div>
    </div>

    <div class="container py-2">
      <div class="row">
        <div class="col-auto">
          <div class="btn-group-vertical">
            <a class="btn btn-sm btn-outline-secondary" data-bs-toggle="collapse" href="#collapseCommitmentReport" role="button" aria-expanded="false" aria-controls="collapseCommitmentReport">
              Commitments
            </a>
            <a class="btn btn-sm btn-outline-secondary" data-bs-toggle="collapse" href="#collapseContributionReport" role="button" aria-expanded="false" aria-controls="collapseContributionReport">
              Contributions
            </a>
          </div>
        </div>
        <div class="col">
      <div class="collapse" id="collapseCommitmentReport">
        <div class="card small py-1 mb-1" data-controller="reports">
          <%= render "fdn/reporting/commitments/form" %>
        </div>
      </div>
      <div class="collapse" id="collapseContributionReport">
        <div class="card small py-1 mb-1" data-controller="reports">
          <%= render "fdn/reporting/contributions/form" %>
        </div>
      </div>

        </div>
      </div>


    </div>
    
  </div>
</div>

app/views/fdn/reporting/reports/organization_list.html.erb
<% provide(:title, "#{@foundation.short_name} Organizations List") %>

<div>
  <% @organizations.each do |organization| %>
    <%= organization.name %><br/>
  <% end %>
</div>