config/routes.rb
Rails.application.routes.draw do
    
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  resources :users, excpet: [:show]
  get "users/cancel/:id", to: "users#cancel", as: "users_cancel"
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  root "fdn/foundations#index"

  scope module: 'fdn' do
    # charts
    get "foundation/:foundation_id/charts/top-donors", to: "charts#top_donors", as: "charts_top_donors"
    get "foundation/:foundation_id/charts/contribution-time-line", to: "charts#contribution_time_line", as: "charts_contribution_time_line"
    
    get "foundation/cancel", to: "foundations#cancel"
    resources :foundations, except: [:show] do
      get "dashboard", on: :member
      get "settings", on: :member
      delete "remove-image-logo", to: "foundations#remove_image_logo", as: "remove_image_logo"
      delete "remove-image-header", to: "foundations#remove_image_header", as: "remove_image_header"
      namespace "reporting" do
        get "dashboard", to: "reports#dashboard"
        get "organization_list", to: "reports#organization_list"
        get "commitment", to: "reports#get_commitment"
        get "contribution", to: "reports#get_contribution"
        post "commitment_report", to: "reports#show_commitment"
        post "contribution_report", to: "reports#show_contribution"
      end
      get "organizations/sort", to: "organizations#sort"
      resources :organizations do
        get "cancel", on: :member
        get "contributions", on: :member
        get "commitments", on: :member
      end
      scope module: 'accounting' do
        resources :bank_accounts do 
          get "cancel", on: :member
          resources :checks, shallow: true, except: [:show]
          get "reconciliations/cancel", to: "reconciliations#cancel"
          post "reconciliations/new_next", to: "reconciliations#new_next"
          resources :reconciliations, shallow: true, except: [:edit, :update]
        end
      end
      scope module: 'donations' do
        get "contributions/new_next", to: "contributions#new_next"
        get "commitments/new_next", to: "commitments#new_next"
        get "contributions/sort", to: "contributions#sort"
        get "commitments/sort", to: "commitments#sort"
        resources :contributions do
          get "cancel", on: :member
        end
        resources :commitments do
          get "cancel", on: :member
          get "contribution/new", to: "commitments#new_contribution"
          post "contributions", to: "commitments#create_contribution"
          get "contribution/:id", to: "commitments#edit_contribution", as: "contribution"
          patch "contribution/:id", to: "commitments#update_contribution"
          delete "contribution/:id", to: "commitments#destroy_contribution"
        end
      end
      namespace :settings do
        resources :donors, except: [:show]
        resources :funding_sources, except: [:show]
        resources :organization_types, except: [:show]
      end
    end
  end

end

app/controllers/fdn/contributions/commitments_controller.rb
class Fdn::Contributions::CommitmentsController < Fdn::BaseController
  before_action :set_commitment, only: %i[ show edit update destroy ]

  def index
    @commitments = Commitment.organization_commitments(@foundation.organization_ids)
    render turbo_stream: [
      turbo_stream.replace("main_content", partial: "index")
    ]      
  end

  def cancel
    if params[:id].to_i != -1
      set_commitment
      render turbo_stream: [
        params[:show].to_i == 0 ? turbo_stream.replace(@commitment, partial: "commitment", locals: {commitment: @commitment}) : turbo_stream.replace(@commitment, partial: "show")
      ]
    else
      flash.now[:notice] = "New Commitment Wizard canceled."
      render turbo_stream: [
        turbo_stream.replace("messages", partial: "layouts/messages"), 
        turbo_stream.replace(Commitment.new, partial: "new_placeholder")
      ]
    end
  end

  def new_next
    if !params[:organization_id].blank?
      @organization = @foundation.organizations.where(id: params[:organization_id].to_i).take
      if @organization.present?
        @commitment = @organization.commitments.new
      else
        flash.now[:alert] = "Organization selected was not found!!."
        render :cancel
      end
    else
      flash.now[:alert] = "Error with wizard no organization selected!"
      render :cancel
    end
  end

  def show
    render turbo_stream: [
      turbo_stream.replace("commitments-main", partial: "show")
    ] 
  end

  def new
    params[:query].blank? ?  @organizations = Organization.none : @organizations = @foundation.organizations.filter_by_name(params[:query]).sort_name_up
  end

  def edit
    @param_show = params[:show].to_i
  end

  def create
    @commitment = Commitment.new(commitment_params)
    if @commitment.save
      flash.now[:notice] = "Commitment was successfully created."
      render turbo_stream: [
        turbo_stream.replace("messages", partial: "layouts/messages"), 
        turbo_stream.replace(Commitment.new, partial: "new_placeholder"), 
        turbo_stream.replace("commitment-list", partial: "commitment_list", locals: {commitments: Commitment.organization_commitments(@foundation.organization_ids)})
      ]        
    else
      render :new_next, status: :unprocessable_entity
    end
  end

  def update
    if @commitment.update(commitment_params)
      flash.now[:notice] = "Commitment was successfully updated."
      render turbo_stream: [
        turbo_stream.replace("messages", partial: "layouts/messages"), 
        params[:commitment][:show] == "1" ? 
        turbo_stream.replace(@commitment, partial: "show") : turbo_stream.replace(@commitment, partial: "commitment", locals: {commitment: @commitment})
      ]
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @commitment.destroy
    @commitments = Commitment.organization_commitments(@foundation.organization_ids)
    flash.now[:notice] = "Commitment was successfully destroyed."
    render turbo_stream: [
      turbo_stream.replace("messages", partial: "layouts/messages"), 
      params[:show].to_i == 1 ? 
      turbo_stream.replace("main_content", partial: "index") : turbo_stream.replace("commitment-list", partial: "commitment_list", locals: {commitments: @commitments})
    ] 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commitment
      @commitment = Commitment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def commitment_params
      params.require(:commitment).permit( :organization_id, :start_at, :end_at, 
        :number_payments, :amount, :code )
    end
end

app/controllers/fdn/donations/contributions_controller.rb
class Fdn::Donations::ContributionsController < Fdn::BaseController
  before_action :set_contribution, only: %i[ show edit update destroy ]
  before_action :set_filter_params, only: %i[ cancel sort]
  
  def index
    @pagy, @contributions = pagy(Contribution.none)
    render turbo_stream: [
      turbo_stream.replace("main_content", partial: "index")
    ]  
  end
  
  def cancel
    if params[:id].to_i != -1
      set_contribution
      render turbo_stream: [
        params[:show].to_i ==  APP_CONSTANTS.contribution.show.false ? 
        turbo_stream.replace(@contribution, partial: "contribution", locals: {contribution: @contribution}) : turbo_stream.replace(@contribution, partial: "show")
      ]
    else
      flash.now[:notice] = "New Contribution Wizard canceled."
      render turbo_stream: [
        turbo_stream.replace("messages", partial: "layouts/messages"), 
        turbo_stream.replace(Contribution.new, partial: "new_button")
      ]
    end
  end

  def sort
    @pagy, @contributions = pagy(ContributionsFilter.new.process_request(Contribution.organization_contributions(@foundation.organization_ids).open_contributions, @by, @dir))
    render turbo_stream: [
      turbo_stream.replace("contribution-list", partial: "contribution_list", locals: {contributions: @contributions})
    ] 
  end

  def new_next
    if !params[:organization_id].blank?
      @organization = @foundation.organizations.where(id: params[:organization_id].to_i).take
      if @organization.present?
        @contribution = @organization.contributions.new
        @contribution.build_check
      else
        flash.now[:alert] = "Organization selected was not found!!."
        render :new, status: :unprocessable_entity
      end
    else
      flash.now[:alert] = "Error with wizard no organization selected!"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    render turbo_stream: [
      turbo_stream.replace("contributions-main", partial: "show")
    ]      
  end

  def new
    params[:query].blank? ?  @organizations = Organization.none : @organizations = @foundation.organizations.filter_by_name(params[:query]).sort_name_up
  end

  def edit
    @param_show = params[:show].to_i
  end

  def create
    @contribution = Contribution.new(contribution_params)
    if @contribution.save
      @pagy, @contributions = pagy(Contribution.organization_contributions(@foundation.organization_ids).open_contributions.sort_date_up)
      flash.now[:notice] = "Contribution was successfully created."
      render turbo_stream: [
        turbo_stream.replace("messages", partial: "layouts/messages"), 
        turbo_stream.replace(Contribution.new, partial: "new_button"), 
        turbo_stream.replace("contribution-list", partial: "contribution_list", locals: {contributions: @contributions})
      ]  
    else
      render :new_next, status: :unprocessable_entity
    end
  end

  def update
    if @contribution.update(contribution_params)
      flash.now[:notice] = "Contribution was successfully updated."
      render turbo_stream: [
        turbo_stream.replace("messages", partial: "layouts/messages"), 
        params[:contribution][:show].to_i ==  APP_CONSTANTS.contribution.show.true ? 
        turbo_stream.replace(@contribution, partial: "show") : turbo_stream.replace(@contribution, partial: "contribution", locals: {contribution: @contribution})
      ]
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @contribution.destroy
      @pagy, @contributions = pagy(Contribution.organization_contributions(@foundation.organization_ids).open_contributions.sort_date_up)
      flash.now[:notice] = "Contribution was successfully destroyed."
      render turbo_stream: [
        turbo_stream.replace("messages", partial: "layouts/messages"), 
        params[:show].to_i == APP_CONSTANTS.contribution.show.true ? 
        turbo_stream.replace("main_content", partial: "index") : turbo_stream.replace("contribution-list", partial: "contribution_list", locals: {contributions: @contributions})
      ] 
    else
      flash.now[:notice] = "Contribution is already cleared cannot be deleted."
      render turbo_stream: [
        turbo_stream.replace("messages", partial: "layouts/messages")
      ]
    end
  end

  private

    def set_filter_params
      params[:page].blank? ? @page = "1" : @page = params[:page]
      params[:by].blank? ? @by = APP_CONSTANTS.contribution.sort.date : @by = params[:by].to_i
      params[:dir].blank? ? @dir = APP_CONSTANTS.contribution.sort_direction.up : @dir = params[:dir].to_i
    end

    def set_contribution
      @contribution = Contribution.find(params[:id])
    end

    def contribution_params
      params.require(:contribution).permit(:donor_id, :funding_source_id, :organization_id, :in_kind,
        check_attributes: [ 
            :id, :check_number, :transaction_at, :description, :amount, :bank_account_id
            ])
    end
end

app/controllers/fdn/reporting/reports_controller.rb
class Fdn::Reporting::ReportsController < Fdn::BaseController

  def dashboard
    render turbo_stream: [
      turbo_stream.replace("main_content", partial: "dashboard")
    ]    
  end

  def organization_list
    set_organization_filter_params
    @organizations = OrganizationsFilter.new.process_request(@foundation.organizations, @query, @by, (@dir == 1 ? @dir = 2 : @dir = 1))
    pdf = generate_pdf("Organization List", nil, "Portrait", "fdn/reporting/organizations/list")
    send_data(pdf, filename: "organization_list", type: "application/pdf", disposition: :inline)  
  end

  def get_commitment
  end

  def get_contribution
  end

  def show_contribution
    contribution_report_form = ContributionReportForm.new(contribution_params)
    @start_at = Date.parse(contribution_report_form.starting_date)
    @end_at = Date.parse(contribution_report_form.ending_date)
    if contribution_report_form.types.include?("0")
      org_ids = @foundation.organization_ids
    else
      org_ids = @foundation.organizations.types(contribution_report_form.types)
    end
    @contributions = Contribution.organization_contributions(org_ids).transactions_during(@start_at, @end_at)
    if !contribution_report_form.funds.include?("0")
      @contributions = @contributions.funds(contribution_report_form.funds)
    end
    if !contribution_report_form.donors.include?("0")
      @contributions = @contributions.donors(contribution_report_form.donors)
    end
    @contributions = @contributions.sort_date_up
    pdf = generate_pdf("Contributions", "fdn/reporting/contributions/header", "Portrait", "fdn/reporting/contributions/summary")
    send_data(pdf, filename: "contribution_report", type: "application/pdf", disposition: :inline)
  end

  def show_commitment
    commitment_report_form = CommitmentReportForm.new(commitment_params)
    if commitment_report_form.state == "open" && commitment_report_form.sort == "alpha"
      @commitments = Commitment.organization_commitments(@foundation.organization_ids).not_completed.sort_organization_up
    elsif commitment_report_form.state == "open" && commitment_report_form.sort == "date"
      @commitments = Commitment.organization_commitments(@foundation.organization_ids).not_completed.sort_start_date_up
    elsif commitment_report_form.state == "closed" && commitment_report_form.sort == "date"
      @commitments = Commitment.organization_commitments(@foundation.organization_ids).completed.sort_start_date_up
    else
      @commitments = Commitment.organization_commitments(@foundation.organization_ids).completed.sort_organization_up
    end
    if commitment_report_form.format == "detailed"
      additional_header = nil
      template = "fdn/reporting/commitments/detailed"
      orientation = "Portrait"
    else
      additional_header = "fdn/reporting/commitments/summary_header"
      template = "fdn/reporting/commitments/summary"
      orientation = "Landscape"
    end
    pdf = generate_pdf("Commitments", additional_header, orientation, template)
    send_data(pdf, filename: "commitment_report", type: "application/pdf", disposition: :inline)  
  end

  private

  def commitment_params
    params.require(:commitment_report_form).permit(:format, :state, :sort)
  end

  def contribution_params
    params.require(:contribution_report_form).permit(:starting_date, :ending_date, funds:[], donors:[], types:[])
  end

  def generate_pdf(title, additional_header, orientation, template)
    WickedPdf.new.pdf_from_string(
      render_to_string(template: template, formats: [:html], layout: "pdf" ),
      # margin: { top: 10, bottom: 10, left: 10, right: 10 }, 
      header: { content: render_to_string(template: "shared/pdf/header", 
                  formats: [:html], 
                  layout: "pdf_section", 
                  locals: { title: title, additional_header: additional_header })
              },
      footer: { content: render_to_string(template: "shared/pdf/footer", 
                  formats: [:html], 
                  layout: "pdf_section") 
                  # right: "[page] of [topage]" 
              },
              orientation: orientation
    )  
  end
  
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/fdn/reporting/contributions/_form.html.erb
<%= turbo_frame_tag "report_form" do %>
  <%= form_with model: ContributionReportForm.new, url: foundation_reporting_contribution_report_path(@foundation), html: {id: "contribution_report"} do |f| %>
    <div class="card-body py-1">

      <div class="row align-items-center pb-1">
        <div class="col-md-1 col-lg-2">
          <%= f.label :starting_date, "Start", class: "badge text-bg-secondary" %>
        </div>
        <div class="col-md-5 col-lg-4">
          <%= f.date_field :starting_date, class: "form-control form-control-sm" %>  
        </div>
        <div class="col-md-1  col-lg-2">
          <%= f.label :ending_date, "End", class: "badge text-bg-secondary" %>
        </div>
        <div class="col-md-5 col-lg-4">
          <%= f.date_field :ending_date, class: "form-control form-control-sm" %>  
        </div>
      </div>
      <div class="border p-1 mt-1">
      <div class="row pb-1">
        <div class="col-md-6 col-lg-4">
          <div class="row mx-0">
            <div class="col py-1 ps-2">
              <span class="badge text-bg-secondary">Select Fund(s)</span>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <%= f.select(:funds, get_select_options_for_funding_sources(@foundation, true), 
                                          { :selected => 0, :multiple => true, :size => 5 }, 
                                          { class: "form-select form-select-sm" }) %>
            </div>
          </div>          
        </div>
        <div class="col-md-6 col-lg-4">
          <div class="row mx-0">
            <div class="col ps-2 py-1">
              <span class="badge text-bg-secondary">Select Donor(s)</span>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <%= f.select(:donors, get_select_options_for_donors(@foundation, true),
                                          { :selected => 0, :multiple => true, :size => 5 }, 
                                          { class: "form-select form-select-sm" }) %>
            </div>
          </div>          
          
        </div>
        <div class="col-md-6 col-lg-4">
          <div class="row mx-0">
            <div class="col ps-2 py-1">
              <span class="badge text-bg-secondary">Select Type(s)</span>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <%= f.select(:types, get_select_options_for_organization_types(@foundation, true), 
                                              { :selected => 0, :multiple => true, :size => 5 } , 
                                              { class: "form-select form-select-sm" }) %>
            </div>
          </div>          
        </div>
      </div>
      </div>
      <div class="pt-2 d-grid gap-1">
        <button type="button" class="btn btn-outline-secondary btn-sm"               
                data-action="click->reports#print_contribution">
          <i class="bi bi-printer pe-1"></i>Print Report
        </button>          
      </div> 
      
    </div>
  <% end %>
<% end %>  

app/views/fdn/reporting/contributions/_header.html.erb
<div class="table">
  <div class="row">
    <div class="col w-39"></div>
    <div class="col w-6"><%= @start_at.strftime("%m/%d/%Y") %></div>
    <div class="col w-1 text-center"> - </div>
    <div class="col w-6"><%= @end_at.strftime("%m/%d/%Y") %></div>
  </div>
  <div class="row header ps-1 pt-1">
    <div class="col w-6">Date</div>
    <div class="col w-16">Organization</div>
    <div class="col w-7">City</div>
    <div class="col w-4">St</div>
    <div class="col w-5">Donor</div>
    <div class="col w-5">CK #</div>
    <div class="col w-7 text-end pe-2">Amount</div>
  </div>
</div>

app/views/fdn/reporting/contributions/summary.html.erb
<% provide(:title, "#{@foundation.short_name} Contribution Report") %>

<div class="table">
  <% @contributions.each do |contribution| %>
    <div class="row ps-1 pt-1">
      <div class="col w-6">
        <%= contribution.check.transaction_at.strftime("%m/%d/%Y") %>
      </div>
      <div class="col w-16">
        <%= contribution.organization.name %>
      </div>
      <div class="col w-7">
        <%= contribution.organization.city %>
      </div>
      <div class="col w-4">
        <%= contribution.organization.state %>
      </div>
      <div class="col w-5">
        <%= contribution.donor.code %>
      </div>
      <div class="col w-5">
        <%= contribution.check.check_number %>
      </div>
      <div class="col w-7 text-end">
        <%= contribution.check.amount.format %>
      </div>
    </div>
  <% end %>
</div>